import shutil

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from app.api.deps import get_db
from app.schemas import (
    ClientDataImportResponse,
    ClientDataStatusResponse,
    ImportResultRead,
)
from app.services.bank_import import BankImportService
from app.services.client_data_upload import (
    database_counts,
    expected_file_labels,
    get_skip_report_path,
    run_client_data_import,
    stage_client_data_files,
)

router = APIRouter(prefix="/imports", tags=["imports"])


@router.post("/deposits", response_model=ImportResultRead)
async def import_deposits(
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
) -> ImportResultRead:
    content = await file.read()
    service = BankImportService(db)
    result = service.import_deposits(content, filename=file.filename or "upload.xlsx")
    return ImportResultRead(
        filename=result.filename,
        row_count=result.row_count,
        imported_count=result.imported_count,
        skipped_count=result.skipped_count,
        error_count=result.error_count,
        errors=[e.to_dict() for e in result.errors],
        import_batch_id=str(result.import_batch_id) if result.import_batch_id else None,
    )


@router.get("/client-data/status", response_model=ClientDataStatusResponse)
def client_data_status(db: Session = Depends(get_db)) -> ClientDataStatusResponse:
    """Current database counts and expected ClientData file roles."""
    return ClientDataStatusResponse(
        database_counts=database_counts(db),
        expected_files=expected_file_labels(),
    )


@router.post("/client-data", response_model=ClientDataImportResponse)
async def import_client_data_files(
    client_list: UploadFile = File(..., description="client list to print.xlsx"),
    management: UploadFile = File(..., description="Management expenses sheet.xlsx"),
    bank: UploadFile | None = File(None, description="Bank Account example.xlsx"),
    credit_card_1: UploadFile | None = File(None, description="credit card 1 example.xlsx"),
    credit_card_2: UploadFile | None = File(None, description="credit card 2 example.xlsx"),
    reset: bool = Form(False),
    confirm_reset: bool = Form(False),
    db: Session = Depends(get_db),
) -> ClientDataImportResponse:
    """Import the full ClientData Excel bundle (same pipeline as scripts/import_client_data.py).

    Required: client_list + management.
    Optional: bank, credit_card_1, credit_card_2.
    Set reset=true and confirm_reset=true to wipe all tables before importing.
    """
    if reset and not confirm_reset:
        raise HTTPException(
            status_code=400,
            detail="confirm_reset must be true when reset is requested",
        )

    data_dir, files_used = await stage_client_data_files(
        client_list=client_list,
        management=management,
        bank=bank,
        credit_card_1=credit_card_1,
        credit_card_2=credit_card_2,
    )
    try:
        return run_client_data_import(
            data_dir=data_dir,
            files_used=files_used,
            reset=reset,
            db=db,
        )
    finally:
        shutil.rmtree(data_dir, ignore_errors=True)


@router.get("/client-data/reports/{report_id}")
def download_client_data_skip_report(report_id: str) -> FileResponse:
    """Download the Excel skip report generated by a client-data import."""
    path = get_skip_report_path(report_id)
    return FileResponse(
        path,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        filename=f"import_skipped_rows_{report_id[:8]}.xlsx",
    )
