import shutil

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from app.api.deps import get_db
from app.schemas import (
    ClientDataImportJobAccepted,
    ClientDataImportJobStatus,
    ClientDataStatusResponse,
    ImportResultRead,
)
from app.services.bank_import import BankImportService
from app.services.client_data_upload import (
    database_counts,
    expected_file_labels,
    get_skip_report_path,
    stage_client_data_files,
)
from app.services.import_jobs import (
    create_staged_job_dir,
    enqueue_client_data_import,
    get_import_job,
)

router = APIRouter(prefix="/imports", tags=["imports"])


@router.post("/deposits", response_model=ImportResultRead)
async def import_deposits(
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
) -> ImportResultRead:
    """Legacy bank-deposit Excel import (CLI/admin). Prefer Data Import in the UI."""
    content = await file.read()
    service = BankImportService(db)
    result = service.import_deposits(content, filename=file.filename or "upload.xlsx")
    return ImportResultRead(
        filename=result.filename,
        row_count=result.row_count,
        imported_count=result.imported_count,
        skipped_count=result.skipped_count,
        error_count=result.error_count,
        errors=[e.to_dict() for e in result.errors],
        import_batch_id=str(result.import_batch_id) if result.import_batch_id else None,
    )


@router.get("/client-data/status", response_model=ClientDataStatusResponse)
def client_data_status(db: Session = Depends(get_db)) -> ClientDataStatusResponse:
    """Current database counts and expected ClientData file roles."""
    return ClientDataStatusResponse(
        database_counts=database_counts(db),
        expected_files=expected_file_labels(),
    )


@router.post(
    "/client-data",
    response_model=ClientDataImportJobAccepted,
    status_code=202,
)
async def import_client_data_files(
    client_list: UploadFile = File(..., description="client list to print.xlsx"),
    management: UploadFile = File(..., description="Management expenses sheet.xlsx"),
    bank: UploadFile | None = File(None, description="Bank Account example.xlsx"),
    credit_card_1: UploadFile | None = File(None, description="credit card 1 example.xlsx"),
    credit_card_2: UploadFile | None = File(None, description="credit card 2 example.xlsx"),
    reset: bool = Form(False),
    confirm_reset: bool = Form(False),
) -> ClientDataImportJobAccepted:
    """Queue a ClientData Excel import (background job — poll GET .../jobs/{job_id}).

    Required: client_list + management.
    Optional: bank, credit_card_1, credit_card_2.
    Set reset=true and confirm_reset=true to wipe all tables before importing.
    """
    if reset and not confirm_reset:
        raise HTTPException(
            status_code=400,
            detail="confirm_reset must be true when reset is requested",
        )

    job_id, files_dir = create_staged_job_dir()
    try:
        _, files_used = await stage_client_data_files(
            client_list=client_list,
            management=management,
            bank=bank,
            credit_card_1=credit_card_1,
            credit_card_2=credit_card_2,
            target_dir=files_dir,
        )
        meta = enqueue_client_data_import(
            job_id=job_id,
            files_used=files_used,
            reset=reset,
        )
    except HTTPException:
        shutil.rmtree(files_dir.parent, ignore_errors=True)
        raise
    except RuntimeError as exc:
        shutil.rmtree(files_dir.parent, ignore_errors=True)
        raise HTTPException(status_code=409, detail=str(exc)) from exc
    except Exception:
        shutil.rmtree(files_dir.parent, ignore_errors=True)
        raise

    return ClientDataImportJobAccepted(
        job_id=meta["job_id"],
        status=meta["status"],
        message=meta.get("message") or "Import queued",
    )


@router.get("/client-data/jobs/{job_id}", response_model=ClientDataImportJobStatus)
def client_data_import_job_status(job_id: str) -> ClientDataImportJobStatus:
    """Poll status of a background ClientData import job."""
    meta = get_import_job(job_id)
    if meta is None:
        raise HTTPException(status_code=404, detail="Import job not found")
    return ClientDataImportJobStatus(
        job_id=meta.get("job_id", job_id),
        status=meta.get("status", "unknown"),
        message=meta.get("message") or "",
        error=meta.get("error"),
        reset=bool(meta.get("reset")),
        files_used=list(meta.get("files_used") or []),
        result=meta.get("result"),
        created_at=meta.get("created_at"),
        updated_at=meta.get("updated_at"),
    )


@router.get("/client-data/reports/{report_id}")
def download_client_data_skip_report(report_id: str) -> FileResponse:
    """Download the Excel skip report generated by a client-data import."""
    path = get_skip_report_path(report_id)
    return FileResponse(
        path,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        filename=f"import_skipped_rows_{report_id[:8]}.xlsx",
    )
